### ISSUE TITLE
Use different axios instance?

### ISSUE THREAD

**Issue by dnldsht** [janiskelemen/formvuelar#11]
I cant find a way to use a custom instance of axios? 

It will be nice to use it so you can use the interceptors, a baseUrl, default headers and other stuff.

I implemented it like this but don't know if its the right way
```
...

let method = this.multipart && (this.method == 'patch' || this.method == 'put') ? 'post' : this.method

// this chage
let _axios = this.axios || this.$http || axios

_axios({
 method: method,
 url: this.url,

...
```

**Comment by janiskelemen** [comment]
Hi,

you can add custom axios headers using the config -> https://formvuelar.netlify.com/#/config

**Comment by dnldsht** [comment]
I've seen that you can use custom headers, but it's not the same as using
your axios instance

**Comment by janiskelemen** [comment]
Unfortunately, it's not possible to share the same instance. However, all additional headers and configs for axios can be set via the global formvuelar config.
