### ISSUE TITLE
FvlForm.vue

### ISSUE THREAD

**Issue by Barrykilby** [janiskelemen/formvuelar#3]
Hi Janis,

I have been having an issue receiving files uploaded via FvlMultiFile.vue (not tested dropzone), server-side I'm not receiving the files just a string of File, File, File.

From what I can see: 

`  Object.keys(rawData).map(e => {
            formData.append(e, rawData[e])
        })`

Is not picking up on the fact there are multiple files in the array representing the multiple files.

Barry

**Comment by Barrykilby** [comment]
Hi Janis,

This seems to do the trick, I'm no JS boffin so feel free to facepalm!

`        Object.keys(rawData).forEach(e => {
		      if(rawData[e] instanceof Object) {
			      Object.keys(rawData[e]).forEach(f => {
				      if (rawData[e][f] instanceof File) {
					      formData.append(e+'[]', rawData[e][f])
                      } else {
					      formData.append(e, rawData[e])
                      }
                  });
              } else {
			      formData.append(e, rawData[e])
		      }
	      });`

Barry

**Comment by janiskelemen** [comment]
I have added your fix to version 0.1.18
