### ISSUE TITLE
@error response

### ISSUE THREAD

**Issue by Xationch** [janiskelemen/formvuelar#8]
Hey,

It should be changed in the file FvlForm.vue :

```javascript
// from
$this.$emit('error', error)
// to
$this.$emit('error', error.response)
```

Otherwise we can not use the returned object on the component
```javascript
<FvlForm @error="onError">
```

```javascript
onError(error) {
   console.log(error.data)
  // from: undefined
 // to: Error Object
}
```
Look for the explanation https://github.com/axios/axios/issues/960#issuecomment-309287911

Having forked your code and modified it a bit I do not know if it's the same with formvuelar. Seem yes.

**Comment by janiskelemen** [comment]
Thank's I'll fix this.
